serve:
  cookies:
    same_site_mode: Lax
  public:
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3002
        - http://localhost:3003
      allowed_methods:
        - GET
        - POST
        - OPTIONS
      allowed_headers:
        - Authorization
        - Content-Type

urls:
  self:
    issuer: http://localhost:4444
  login: http://localhost:3001/login
  consent: http://localhost:3001/consent

secrets:
  system:
    - local-development-system-secret-change-me

strategies:
  access_token: opaque

ttl:
  refresh_token: 720h

oauth2:
  grant:
    refresh_token:
      rotation_grace_period: 10s

oidc:
  subject_identifiers:
    supported_types:
      - public
